version: '3.8'

services:
  web:
    container_name: nextjs-app
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # avoid overwriting node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
